services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api-cnab
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Rabbit__Host=rabbitmq
      - ConnectionStrings__ReadDatabase=Host=postgres;Port=5432;Database=cnab_consumer;Username=admin;Password=root
    depends_on: [ postgres, rabbitmq ]
    ports: ["8080:8080"]

  consumer:
    build: ./consumer-cnab
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=cnab_consumer;Username=admin;Password=root
      - Rabbit__Host=rabbitmq
    depends_on: [ postgres, rabbitmq ]

  client:
    build: ./client-cnab
    depends_on: [ api ]
    ports: ["4201:80"]
    
volumes:
  postgres_data:
